### ISSUE TITLE
Sometimes Link Descriptions Include HTML

### ISSUE THREAD

**Issue by Archer70** [WildPHP/module-linksniffer#10]
Linking this page: https://www.mozilla.org/en-US/firefox/developer/
results in the following. I've seen this before, and I'm not sure what's causing it.

![screenshot from 2017-09-26 18-16-32](https://user-images.githubusercontent.com/2660927/30891343-a8deccf6-a2e7-11e7-928b-901691adae0a.png)

**Comment by NanoSector** [comment]
Just ran some tests but they check out: https://regex101.com/r/kKkxHi/1/

Not sure what is causing it in this case.

**Comment by Archer70** [comment]
¯\\\_(ツ)_/¯
It's either fixed, or the page has changed, because it's not doing it anymore.

**Comment by NanoSector** [comment]
it tends to happen on more pages though so I'll leave this open for now

**Comment by NanoSector** [comment]
Botergos still does this:

```
<NanoSector> https://www.mozilla.org/en-US/firefox/developer/ Botergos 
<Botergos> [NanoSector] Firefox Developer Edition</title> <meta name="description" content="Firefox Developer Edition is the blazing fast browser that offers cutting edge developer tools and the latest features like CSS Grid support and framework debugging"> <meta property="og:type" content="website"> <meta property="og:site_name" content="Mozilla"> <meta property="og:locale" content="en_US"> <meta property="og:url" content="https
```

EDIT: It works properly on a test bot though... Very strange :\

**Comment by NanoSector** [comment]
Oh, the Firefox Developer page has multiple </title> tags in it. Botergos is likely slower in looping due to the device it runs on which allows for more page data to be downloaded, hence it hitting the second tag.
